main: com.teunjojo.SimpleAutoRestart
name: SimpleAutoRestart
version: ${pluginVersion}
description: Really simple Spigot plugin that automatically restarts your server.
api-version: 1.13
folia-supported: true
author: teunjojo
website: https://www.teunjojo.com
commands:
  simpleautorestart:
    description: Main SimpleAutoRestart command
    aliases: [sar, autorestart]
    usage: "Usage: /<command> set <hour> <minute> [day]"
    permission: simpleautorestart.use
    default: op
permissions:
  simpleautorestart.use:
    description: Permission to use SimpleAutoRestart
    default: op
