main: com.teunjojo.SimpleAutoRestart
name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.13
folia-supported: false
author: teunjojo
website: ${project.url}
commands:
  simpleautorestart:
    description: Main SimpleAutoRestart command
    aliases: [sar, autorestart]
    usage: "Usage: /<command> set <hour> <minute> [day]"
    permission: simpleautorestart.use
    default: op
